### PR TITLE
adding user based rbenv installs:

### PR DESCRIPTION
**Pull request by majormoses**
- adding safe (does not break if rbenv_root does not exist) attribute driven based recipe
- adding test cookbook
- adding additonal serverspec tests

### CODE REVIEW

**Comment by huynt1979** [comment]
[test]

**Comment by huynt1979** [comment]
[test]

**Comment by huynt1979** [comment]
[test]

**Comment by majormoses** [comment]
[test]

**Comment by huynt1979** [comment]
[test]

**Comment by huynt1979** [comment]
lg2m

**Pull request merged**
